#!/bin/bash
# ==============================================================================
# DNSAdmin cPanel Standard Hooks Installer
# Target OS: Linux with cPanel/WHM
# Usage:
#   curl -sS https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main/install-cpanel.sh | bash -s -- --controller-url http://your-controller-ip:5380 --token <your-server-api-key>
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this installation script as root."
  exit 1
fi

show_help() {
  echo "Usage: $0 --controller-url <url> --token <token>"
  echo "Options:"
  echo "  --controller-url   URL of the central DNSAdmin controller"
  echo "  --token            Server API key generated by the controller for this server"
  exit 0
}

# Parse options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --controller-url) CONTROLLER_URL="$2"; shift ;;
    --token) TOKEN="$2"; shift ;;
    -h|--help) show_help ;;
    *) echo "Unknown option: $1"; show_help ;;
  esac
  shift
done

if [ -z "$CONTROLLER_URL" ] || [ -z "$TOKEN" ]; then
  echo "Error: --controller-url and --token are required."
  show_help
fi

# Check if cPanel script manager is present
if [ ! -f "/usr/local/cpanel/bin/manage_hooks" ]; then
  echo "Error: cPanel hook manager (/usr/local/cpanel/bin/manage_hooks) not found on this server."
  exit 1
fi

HOOK_DEST="/usr/local/bin/dnsadmin-cpanel-hook.sh"
RAW_BASE_URL="https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main"

echo "Downloading cPanel integration hook..."
curl -sS -o "$HOOK_DEST" "$RAW_BASE_URL/integrations/cpanel-hook.sh?v=$(date +%s)"
curl -sS -o "/usr/local/bin/dnsadmin-cpanel-sync-all.sh" "$RAW_BASE_URL/integrations/cpanel-sync-all.sh?v=$(date +%s)"

if [ ! -f "$HOOK_DEST" ] || [ ! -s "$HOOK_DEST" ]; then
  echo "Error: Failed to download cPanel hook script."
  exit 1
fi

# Normalize CONTROLLER_URL (strip trailing slash)
CONTROLLER_URL="${CONTROLLER_URL%/}"

# Insert configuration variables
echo "Configuring integration hooks..."
sed -i "s|CONTROLLER_API=\"[^\"]*\"|CONTROLLER_API=\"$CONTROLLER_URL/api/v1/agent\"|g" "$HOOK_DEST"
sed -i "s|AGENT_TOKEN=\"[^\"]*\"|AGENT_TOKEN=\"$TOKEN\"|g" "$HOOK_DEST"

chmod +x "$HOOK_DEST" "/usr/local/bin/dnsadmin-cpanel-sync-all.sh"

# Register WHM Standardized Hooks
echo "Registering Standardized Hooks in WHM..."
# Remove existing registration to prevent duplicate hooks
/usr/local/cpanel/bin/manage_hooks delete --manual --event Zone --stage post --hook "$HOOK_DEST" &>/dev/null

# Register the hook
/usr/local/cpanel/bin/manage_hooks add --manual --category System --event Zone --stage post --hook "$HOOK_DEST"

# Setup 60-second cron job for server heartbeat ping
echo "Setting up 60-second cron heartbeat..."
(crontab -l 2>/dev/null | grep -F -v "dnsadmin/api/v1/agent/heartbeat"; echo "* * * * * curl -s -X POST -H \"X-DNSAdmin-Token: $TOKEN\" $CONTROLLER_URL/api/v1/agent/heartbeat >/dev/null 2>&1") | crontab -

# 5. Create 10-second DNSAdmin Zone Watcher Service
echo "Configuring 10-second DNSAdmin Zone Watcher Daemon..."
WATCHER_SCRIPT="/usr/local/bin/dnsadmin-watcher.sh"
cat << 'EOF' > "$WATCHER_SCRIPT"
#!/bin/bash
HOOK_SCRIPT="/usr/local/bin/dnsadmin-cpanel-hook.sh"
CACHE_DIR="/dev/shm/dnsadmin-cache"
mkdir -p "$CACHE_DIR"

log() {
  echo "[DNSAdmin Watcher] $1" >&2
}

scan_and_sync() {
  for dir in "/var/named" "/var/named/chroot/var/named"; do
    [ -d "$dir" ] || continue
    find "$dir" -maxdepth 1 -type f -name "*.db" ! -name "named.*" 2>/dev/null | while read -r filepath; do
      filename=$(basename "$filepath")
      domain="${filename%.db}"
      if [[ "$domain" != *.* ]]; then
        continue
      fi
      if [[ "$domain" == PROTO.* || "$domain" == localhost* || "$domain" == named.* ]]; then
        continue
      fi
      current_md5=$(md5sum "$filepath" | awk '{print $1}')
      cache_file="$CACHE_DIR/${domain}.md5"
      if [ -f "$cache_file" ]; then
        old_md5=$(cat "$cache_file")
      else
        old_md5=""
      fi
      if [ "$current_md5" != "$old_md5" ]; then
        log "Detected changes in $domain. Triggering sync..."
        "$HOOK_SCRIPT" "$domain" >/dev/null 2>&1 &
        echo "$current_md5" > "$cache_file"
      fi
    done
  done
}

log "Starting DNSAdmin Zone Watcher Daemon..."
while true; do
  scan_and_sync
  sleep 10
done
EOF

chmod +x "$WATCHER_SCRIPT"

# Install Systemd Service
cat << 'EOF' > /etc/systemd/system/dnsadmin-watcher.service
[Unit]
Description=DNSAdmin Zone Watcher Daemon
After=network.target named.service

[Service]
Type=simple
ExecStart=/usr/local/bin/dnsadmin-watcher.sh
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable dnsadmin-watcher &>/dev/null
systemctl restart dnsadmin-watcher &>/dev/null


echo "=================================================="
echo " DNSAdmin cPanel integration successfully installed!"
echo " Hook path: $HOOK_DEST"
echo " Active Hooks Registered:"
/usr/local/cpanel/bin/manage_hooks list | grep -B2 -A2 "dnsadmin"
echo "=================================================="
