#!/bin/bash
# ==============================================================================
# DNSAdmin Nameserver Node Agent Dedicated Installer
# Target OS: Debian/Ubuntu, RHEL/CentOS/AlmaLinux
# Usage:
#   curl -sS https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main/install-node.sh | bash -s -- --controller-url http://your-controller-ip:5380 --token <your-node-token> --ns-name ns1.yourdomain.com
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this installation script as root."
  exit 1
fi

show_help() {
  echo "Usage: $0 --controller-url <url> --token <token> --ns-name <nameserver-name> [--port <port>]"
  echo "Options:"
  echo "  --controller-url   URL of the central DNSAdmin controller"
  echo "  --token            Auth token generated by the controller for this node"
  echo "  --ns-name          FQDN of this nameserver (e.g. ns1.example.com)"
  echo "  --port             Port for the Agent daemon to listen on (default: 5300)"
  exit 0
}

# Parse options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --controller-url) CONTROLLER_URL="$2"; shift ;;
    --token) TOKEN="$2"; shift ;;
    --ns-name) NS_NAME="$2"; shift ;;
    --port) PORT="$2"; shift ;;
    -h|--help) show_help ;;
    *) echo "Unknown option: $1"; show_help ;;
  esac
  shift
done

if [ -z "$CONTROLLER_URL" ] || [ -z "$TOKEN" ] || [ -z "$NS_NAME" ]; then
  echo "Error: --controller-url, --token, and --ns-name are required."
  show_help
fi

NODE_PORT=${PORT:-5300}
INSTALL_DIR="/opt/dnsadmin-node"
ZONES_DIR="$INSTALL_DIR/zones"
NAMED_CONF="$INSTALL_DIR/dnsadmin.zones"
RAW_BASE_URL="https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main"

# Detect Package Manager
if command -v apt-get &>/dev/null; then
  PKG_MAN="apt"
elif command -v dnf &>/dev/null; then
  PKG_MAN="dnf"
elif command -v yum &>/dev/null; then
  PKG_MAN="yum"
else
  echo "Error: Package manager (apt, dnf, yum) not found."
  exit 1
fi

# Install dependencies helper
install_package() {
  if [ "$PKG_MAN" == "apt" ]; then
    apt-get update && apt-get install -y "$1"
  else
    $PKG_MAN install -y "$1"
  fi
}

# 1. Install Node.js & curl
if ! command -v node &>/dev/null; then
  echo "Installing Node.js..."
  if [ "$PKG_MAN" == "apt" ]; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
  elif [ "$PKG_MAN" == "dnf" ] || [ "$PKG_MAN" == "yum" ]; then
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    $PKG_MAN install -y nodejs
  fi
fi

if ! command -v curl &>/dev/null; then
  install_package "curl"
fi

# 2. Install BIND 9 DNS Server
echo "Checking BIND 9 installation..."
BIND_SERVICE="named"
if [ "$PKG_MAN" == "apt" ]; then
  BIND_SERVICE="bind9"
fi

if ! command -v named &>/dev/null; then
  echo "Installing BIND 9..."
  if [ "$PKG_MAN" == "apt" ]; then
    install_package "bind9"
    install_package "bind9utils"
  else
    install_package "bind"
    install_package "bind-utils"
  fi
fi

# 3. Create directories and download agent source files
echo "Downloading Node Agent codebase..."
mkdir -p "$ZONES_DIR"
cd "$INSTALL_DIR" || exit 1

curl -sS -o agent.js "$RAW_BASE_URL/node-agent/agent.js"
curl -sS -o package.json "$RAW_BASE_URL/node-agent/package.json"
curl -sS -o package-lock.json "$RAW_BASE_URL/node-agent/package-lock.json"

# Write default empty zones configuration
touch "$INSTALL_DIR/dnsadmin.zones"
chown -R root:root "$INSTALL_DIR"

# Install production npm packages
echo "Installing Node Agent packages..."
npm install --omit=dev

# 4. Integrate BIND 9 configuration inclusion
echo "Configuring BIND 9 integration..."
NAMED_LOCAL=""
if [ "$PKG_MAN" == "apt" ]; then
  NAMED_LOCAL="/etc/bind/named.conf.local"
else
  NAMED_LOCAL="/etc/named.conf"
fi

if [ -f "$NAMED_LOCAL" ]; then
  if ! grep -q "$NAMED_CONF" "$NAMED_LOCAL"; then
    echo "Adding inclusion statement to $NAMED_LOCAL..."
    if [ "$PKG_MAN" == "apt" ]; then
      echo "include \"$NAMED_CONF\";" >> "$NAMED_LOCAL"
    else
      # RHEL BIND places settings inside main options wrapper, append at end of named.conf
      echo "include \"$NAMED_CONF\";" >> "$NAMED_LOCAL"
    fi
  fi
else
  echo "Warning: BIND local config file not found at $NAMED_LOCAL. Please include \"$NAMED_CONF\" manually."
fi

# Set directory permissions for BIND
if [ "$PKG_MAN" == "apt" ]; then
  chown -R bind:bind "$ZONES_DIR"
  chown bind:bind "$NAMED_CONF"
else
  chown -R named:named "$ZONES_DIR"
  chown named:named "$NAMED_CONF"
fi
chmod 770 "$ZONES_DIR"

# 5. Create Systemd Service Unit
echo "Creating systemd daemon service..."
NODE_PATH=$(which node)

cat <<EOF > /etc/systemd/system/dnsadmin-node-agent.service
[Unit]
Description=DNSAdmin Nameserver Node Agent
After=network.target $BIND_SERVICE.service

[Service]
Type=simple
User=root
WorkingDirectory=$INSTALL_DIR
Environment=PORT=$NODE_PORT
Environment=DNSADMIN_TOKEN=$TOKEN
Environment=DNSADMIN_CONTROLLER_URL=$CONTROLLER_URL
Environment=NODE_NAME=$NS_NAME
Environment=ZONES_DIR=$ZONES_DIR
Environment=NAMED_CONF_PATH=$NAMED_CONF
Environment=RELOAD_CMD="systemctl reload $BIND_SERVICE"
ExecStart=$NODE_PATH agent.js
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# Reload and start services
systemctl daemon-reload
systemctl enable "$BIND_SERVICE"
systemctl restart "$BIND_SERVICE"
systemctl enable dnsadmin-node-agent
systemctl restart dnsadmin-node-agent

echo "=================================================="
echo " DNSAdmin Node Agent successfully installed!"
echo " Nameserver Name: $NS_NAME"
echo " Agent Port: $NODE_PORT"
echo " BIND DNS Server Status: $(systemctl is-active $BIND_SERVICE)"
echo " Node Agent Status: $(systemctl is-active dnsadmin-node-agent)"
echo "=================================================="
