#!/bin/bash
# ==============================================================================
# DNSAdmin Nameserver Node Agent Dedicated Installer
# Target OS: Debian/Ubuntu, RHEL/CentOS/AlmaLinux
# Usage:
#   curl -sS https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main/install-node.sh | bash -s -- --controller-url http://your-controller-ip:5380 --token <your-node-token> --ns-name ns1.yourdomain.com
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this installation script as root."
  exit 1
fi

show_help() {
  echo "Usage: $0 --controller-url <url> --token <token> --ns-name <nameserver-name> [--port <port>] [--ssl]"
  echo "Options:"
  echo "  --controller-url   URL of the central DNSAdmin controller"
  echo "  --token            Auth token generated by the controller for this node"
  echo "  --ns-name          FQDN of this nameserver (e.g. ns1.example.com)"
  echo "  --port             Port for the Agent daemon to listen on (default: 5300)"
  echo "  --ssl              Configure SSL (HTTPS) for this agent using Let's Encrypt"
  exit 0
}

# Parse options
CONTROLLER_URL=""
TOKEN=""
NS_NAME=""
PORT=""
WANT_SSL=0

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --controller-url) CONTROLLER_URL="$2"; shift ;;
    --token) TOKEN="$2"; shift ;;
    --ns-name) NS_NAME="$2"; shift ;;
    --port) PORT="$2"; shift ;;
    --ssl) WANT_SSL=1 ;;
    -h|--help) show_help ;;
    *) echo "Unknown option: $1"; show_help ;;
  esac
  shift
done

# Detect TTY (interactive mode)
IS_INTERACTIVE=0
if [ -t 0 ]; then
  IS_INTERACTIVE=1
fi

if [ "$IS_INTERACTIVE" -eq 1 ]; then
  echo "=================================================="
  echo " Welcome to DNSAdmin Nameserver Agent Installer!"
  echo "=================================================="
  if [ -z "$CONTROLLER_URL" ]; then
    read -p "Enter Central Controller URL (e.g. http://1.2.3.4:5380): " CONTROLLER_URL
  fi
  if [ -z "$TOKEN" ]; then
    read -p "Enter Node Token (API Key from the dashboard): " TOKEN
  fi
  if [ -z "$NS_NAME" ]; then
    read -p "Enter Nameserver Hostname (e.g. ns1.yourdomain.com): " NS_NAME
  fi
  if [ -z "$PORT" ]; then
    read -p "Enter Agent port [default: 5300]: " user_port
    PORT=${user_port:-5300}
  fi
  read -p "Would you like to configure SSL (HTTPS) for this Agent? (y/n) [default: n]: " get_ssl
  if [[ "$get_ssl" =~ ^[Yy]$ ]]; then
    WANT_SSL=1
  fi
else
  if [ -z "$CONTROLLER_URL" ] || [ -z "$TOKEN" ] || [ -z "$NS_NAME" ]; then
    echo "Error: --controller-url, --token, and --ns-name are required in non-interactive mode."
    show_help
  fi
fi

NODE_PORT=${PORT:-5300}
INSTALL_DIR="/opt/dnsadmin-node"
ZONES_DIR="$INSTALL_DIR/zones"
NAMED_CONF="$INSTALL_DIR/dnsadmin.zones"
RAW_BASE_URL="https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main"

# Detect Package Manager
if command -v apt-get &>/dev/null; then
  PKG_MAN="apt"
elif command -v dnf &>/dev/null; then
  PKG_MAN="dnf"
elif command -v yum &>/dev/null; then
  PKG_MAN="yum"
else
  echo "Error: Package manager (apt, dnf, yum) not found."
  exit 1
fi

# Install dependencies helper
install_package() {
  if [ "$PKG_MAN" == "apt" ]; then
    apt-get update && apt-get install -y "$1"
  else
    $PKG_MAN install -y "$1"
  fi
}

# 1. Install/Upgrade Node.js & curl
NEED_INSTALL=0
if ! command -v node &>/dev/null; then
  NEED_INSTALL=1
else
  CURRENT_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
  if [ "$CURRENT_VERSION" -lt 18 ]; then
    echo "Found outdated Node.js version: v$CURRENT_VERSION. Upgrading to Node.js v20..."
    NEED_INSTALL=1
  fi
fi

if [ "$NEED_INSTALL" -eq 1 ]; then
  echo "Installing modern Node.js..."
  if [ "$PKG_MAN" == "apt" ]; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
  elif [ "$PKG_MAN" == "dnf" ] || [ "$PKG_MAN" == "yum" ]; then
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    $PKG_MAN install -y nodejs --disableexcludes=all
  fi
fi

if ! command -v curl &>/dev/null; then
  install_package "curl"
fi

# 2. Install BIND 9 DNS Server
echo "Checking BIND 9 installation..."
BIND_SERVICE="named"
if [ "$PKG_MAN" == "apt" ]; then
  BIND_SERVICE="bind9"
fi

if ! command -v named &>/dev/null; then
  echo "Installing BIND 9..."
  if [ "$PKG_MAN" == "apt" ]; then
    install_package "bind9"
    install_package "bind9utils"
  else
    install_package "bind"
    install_package "bind-utils"
  fi
fi

# 3. Create directories and download agent source files
echo "Purging old agent directories and zone files to perform a clean install..."
if [ -d "$ZONES_DIR" ]; then
  rm -f "$ZONES_DIR"/*
fi
rm -f "$INSTALL_DIR/dnsadmin.zones"

echo "Downloading Node Agent codebase..."
mkdir -p "$ZONES_DIR"
cd "$INSTALL_DIR" || exit 1

curl -sS -o agent.js "$RAW_BASE_URL/node-agent/agent.js"
curl -sS -o package.json "$RAW_BASE_URL/node-agent/package.json"
curl -sS -o package-lock.json "$RAW_BASE_URL/node-agent/package-lock.json"

# Write default empty zones configuration
touch "$INSTALL_DIR/dnsadmin.zones"
chown -R root:root "$INSTALL_DIR"

# Install production npm packages
echo "Installing Node Agent packages..."
npm install --omit=dev

# 4. Integrate BIND 9 configuration inclusion
echo "Configuring BIND 9 integration..."
NAMED_LOCAL=""
if [ "$PKG_MAN" == "apt" ]; then
  NAMED_LOCAL="/etc/bind/named.conf.local"
else
  NAMED_LOCAL="/etc/named.conf"
fi

if [ -f "$NAMED_LOCAL" ]; then
  # Clean up duplicate include entries from previous installations
  sed -i '\/opt\/dnsadmin-node\/dnsadmin.zones/d' "$NAMED_LOCAL"
  
  if ! grep -q "$NAMED_CONF" "$NAMED_LOCAL"; then
    echo "Adding inclusion statement to $NAMED_LOCAL..."
    echo "include \"$NAMED_CONF\";" >> "$NAMED_LOCAL"
  fi

  # Enable BIND to listen on all interfaces and permit public queries (AlmaLinux/CentOS/RHEL)
  if [ "$NAMED_LOCAL" == "/etc/named.conf" ]; then
    echo "Updating BIND named.conf interface and query settings..."
    sed -i '/listen-on/s/127.0.0.1/any/g' "$NAMED_LOCAL"
    sed -i '/listen-on-v6/s/::1/any/g' "$NAMED_LOCAL"
    sed -i '/allow-query/s/localhost/any/g' "$NAMED_LOCAL"
  fi
else
  echo "Warning: BIND local config file not found at $NAMED_LOCAL. Please include \"$NAMED_CONF\" manually."
fi

# Enable public query permission block for Debian/Ubuntu BIND config options
if [ -f "/etc/bind/named.conf.options" ]; then
  if ! grep -q "allow-query" "/etc/bind/named.conf.options"; then
    echo "Updating BIND named.conf.options query settings..."
    sed -i '/options {/a \        allow-query { any; };' "/etc/bind/named.conf.options"
  fi
fi

# Set directory permissions for BIND
if [ "$PKG_MAN" == "apt" ]; then
  chown -R bind:bind "$ZONES_DIR"
  chown bind:bind "$NAMED_CONF"
else
  chown -R named:named "$ZONES_DIR"
  chown named:named "$NAMED_CONF"
fi
chmod 770 "$ZONES_DIR"

# Apply SELinux security context if SELinux is enabled (crucial for RHEL/CentOS/AlmaLinux)
if command -v getenforce &>/dev/null; then
  SELINUX_STATUS=$(getenforce)
  if [ "$SELINUX_STATUS" == "Enforcing" ] || [ "$SELINUX_STATUS" == "Permissive" ]; then
    echo "SELinux detected ($SELINUX_STATUS). Applying BIND zone contexts to $INSTALL_DIR..."
    chcon -R -t named_zone_t "$INSTALL_DIR" &>/dev/null
    if command -v semanage &>/dev/null; then
      semanage fcontext -a -t named_zone_t "$INSTALL_DIR(/.*)?" &>/dev/null
      restorecon -R "$INSTALL_DIR" &>/dev/null
    fi
  fi
fi

# 5. Create Systemd Service Unit
echo "Creating systemd daemon service..."

# Check if agent should run with HTTPS
USE_SSL_VAR="false"
SSL_CERT_VAR=""
SSL_KEY_VAR=""
if [ "$WANT_SSL" -eq 1 ] && [ -n "$NS_NAME" ]; then
  echo "Installing Certbot for standalone SSL..."
  if [ "$PKG_MAN" == "apt" ]; then
    apt-get update
    apt-get install -y certbot
  else
    $PKG_MAN install -y epel-release
    $PKG_MAN install -y certbot --disableexcludes=all
  fi

  # Open firewall port for standalone HTTP verification
  if command -v firewall-cmd &>/dev/null; then
    firewall-cmd --zone=public --add-port=80/tcp --permanent
    firewall-cmd --reload &>/dev/null
  fi
  if command -v ufw &>/dev/null; then
    ufw allow 80/tcp &>/dev/null
  fi

  # Stop any conflicting HTTP services to free port 80 for standalone verification
  systemctl stop apache2 2>/dev/null || systemctl stop httpd 2>/dev/null || systemctl stop nginx 2>/dev/null

  echo "Requesting Let's Encrypt standalone certificate for $NS_NAME..."
  if certbot certonly --standalone -d "$NS_NAME" --non-interactive --agree-tos --register-unsafely-without-email; then
    echo "SSL certificate successfully obtained for $NS_NAME!"
    USE_SSL_VAR="true"
    SSL_CERT_VAR="/etc/letsencrypt/live/$NS_NAME/fullchain.pem"
    SSL_KEY_VAR="/etc/letsencrypt/live/$NS_NAME/privkey.pem"
  else
    echo "Warning: Standalone SSL request failed. Falling back to HTTP..."
  fi
fi

NODE_PATH=$(which node 2>/dev/null || echo "/usr/bin/node")
for ea_node in /opt/cpanel/ea-nodejs20/bin/node /opt/cpanel/ea-nodejs18/bin/node /opt/cpanel/ea-nodejs16/bin/node; do
  if [ -x "$ea_node" ]; then
    NODE_PATH="$ea_node"
    echo "Found EasyApache Node.js binary at $NODE_PATH"
    break
  fi
done

cat <<EOF > /etc/systemd/system/dnsadmin-node-agent.service
[Unit]
Description=DNSAdmin Nameserver Node Agent
After=network.target $BIND_SERVICE.service

[Service]
Type=simple
User=root
WorkingDirectory=$INSTALL_DIR
Environment=PORT=$NODE_PORT
Environment=DNSADMIN_TOKEN=$TOKEN
Environment=DNSADMIN_CONTROLLER_URL=$CONTROLLER_URL
Environment=NODE_NAME=$NS_NAME
Environment=ZONES_DIR=$ZONES_DIR
Environment=NAMED_CONF_PATH=$NAMED_CONF
Environment=RELOAD_CMD="systemctl reload $BIND_SERVICE"
Environment=USE_SSL=$USE_SSL_VAR
Environment=SSL_CERT_PATH=$SSL_CERT_VAR
Environment=SSL_KEY_PATH=$SSL_KEY_VAR
ExecStart=$NODE_PATH agent.js
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# Open Node Agent Port in firewall
if command -v firewall-cmd &>/dev/null; then
  firewall-cmd --zone=public --add-port="$NODE_PORT"/tcp --permanent
  firewall-cmd --reload &>/dev/null
fi
if command -v ufw &>/dev/null; then
  ufw allow "$NODE_PORT"/tcp &>/dev/null
fi

# Reload and start services
systemctl daemon-reload
systemctl enable "$BIND_SERVICE"
systemctl restart "$BIND_SERVICE"
systemctl enable dnsadmin-node-agent
systemctl restart dnsadmin-node-agent

echo "=================================================="
echo " DNSAdmin Node Agent successfully installed!"
echo " Nameserver Name: $NS_NAME"
echo " Agent Port: $NODE_PORT"
echo " BIND DNS Server Status: $(systemctl is-active $BIND_SERVICE)"
echo " Node Agent Status: $(systemctl is-active dnsadmin-node-agent)"
echo "=================================================="
