#!/bin/bash
# ==============================================================================
# DNSAdmin cPanel Standard Hooks Installer
# Target OS: Linux with cPanel/WHM
# Usage:
#   curl -sS https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main/install-cpanel.sh | bash -s -- --controller-url http://your-controller-ip:5380 --token <your-server-api-key>
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this installation script as root."
  exit 1
fi

show_help() {
  echo "Usage: $0 --controller-url <url> --token <token>"
  echo "Options:"
  echo "  --controller-url   URL of the central DNSAdmin controller"
  echo "  --token            Server API key generated by the controller for this server"
  exit 0
}

# Parse options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --controller-url) CONTROLLER_URL="$2"; shift ;;
    --token) TOKEN="$2"; shift ;;
    -h|--help) show_help ;;
    *) echo "Unknown option: $1"; show_help ;;
  esac
  shift
done

if [ -z "$CONTROLLER_URL" ] || [ -z "$TOKEN" ]; then
  echo "Error: --controller-url and --token are required."
  show_help
fi

# Check if cPanel script manager is present
if [ ! -f "/usr/local/cpanel/bin/manage_hooks" ]; then
  echo "Error: cPanel hook manager (/usr/local/cpanel/bin/manage_hooks) not found on this server."
  exit 1
fi

HOOK_DEST="/usr/local/bin/dnsadmin-cpanel-hook.sh"
RAW_BASE_URL="https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main"

echo "Downloading cPanel integration hook..."
curl -sS -o "$HOOK_DEST" "$RAW_BASE_URL/integrations/cpanel-hook.sh?v=$(date +%s)"

if [ ! -f "$HOOK_DEST" ] || [ ! -s "$HOOK_DEST" ]; then
  echo "Error: Failed to download cPanel hook script."
  exit 1
fi

# Normalize CONTROLLER_URL (strip trailing slash)
CONTROLLER_URL="${CONTROLLER_URL%/}"

# Insert configuration variables
echo "Configuring integration hooks..."
sed -i "s|CONTROLLER_API=\"[^\"]*\"|CONTROLLER_API=\"$CONTROLLER_URL/api/v1/agent\"|g" "$HOOK_DEST"
sed -i "s|AGENT_TOKEN=\"[^\"]*\"|AGENT_TOKEN=\"$TOKEN\"|g" "$HOOK_DEST"

chmod +x "$HOOK_DEST"

# Register WHM Standardized Hooks
echo "Registering Standardized Hooks in WHM..."
# Remove existing registration to prevent duplicate hooks
/usr/local/cpanel/bin/manage_hooks delete --manual --event Zone --stage post --hook "$HOOK_DEST" &>/dev/null

# Register the hook
/usr/local/cpanel/bin/manage_hooks add --manual --category System --event Zone --stage post --hook "$HOOK_DEST"

echo "=================================================="
echo " DNSAdmin cPanel integration successfully installed!"
echo " Hook path: $HOOK_DEST"
echo " Active Hooks Registered:"
/usr/local/cpanel/bin/manage_hooks list | grep -B2 -A2 "dnsadmin"
echo "=================================================="
