#!/bin/bash
# ==============================================================================
# DNSAdmin DirectAdmin Hooks Installer
# Target OS: Linux with DirectAdmin
# Usage:
#   curl -sS https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main/install-directadmin.sh | bash -s -- --controller-url http://your-controller-ip:5380 --token <your-server-api-key>
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this installation script as root."
  exit 1
fi

show_help() {
  echo "Usage: $0 --controller-url <url> --token <token>"
  echo "Options:"
  echo "  --controller-url   URL of the central DNSAdmin controller"
  echo "  --token            Server API key generated by the controller for this server"
  exit 0
}

# Parse options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --controller-url) CONTROLLER_URL="$2"; shift ;;
    --token) TOKEN="$2"; shift ;;
    -h|--help) show_help ;;
    *) echo "Unknown option: $1"; show_help ;;
  esac
  shift
done

if [ -z "$CONTROLLER_URL" ] || [ -z "$TOKEN" ]; then
  echo "Error: --controller-url and --token are required."
  show_help
fi

DA_CUSTOM_DIR="/usr/local/directadmin/scripts/custom"
if [ ! -d "$DA_CUSTOM_DIR" ]; then
  echo "Error: DirectAdmin custom scripts directory ($DA_CUSTOM_DIR) not found."
  exit 1
fi

WRITE_HOOK="$DA_CUSTOM_DIR/dns_write_post.sh"
DELETE_HOOK="$DA_CUSTOM_DIR/dns_delete_post.sh"
RAW_BASE_URL="https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main"

echo "Downloading DirectAdmin integration hooks..."
curl -sS -o "$WRITE_HOOK" "$RAW_BASE_URL/integrations/da-hook.sh"
curl -sS -o "$DELETE_HOOK" "$RAW_BASE_URL/integrations/da-delete-hook.sh"

if [ ! -f "$WRITE_HOOK" ] || [ ! -f "$DELETE_HOOK" ]; then
  echo "Error: Failed to download DirectAdmin hook scripts."
  exit 1
fi

# Insert configuration variables
echo "Configuring integration hooks..."
sed -i "s|CONTROLLER_URL=\"[^\"]*\"|CONTROLLER_URL=\"$CONTROLLER_URL\"|g" "$WRITE_HOOK"
sed -i "s|AGENT_TOKEN=\"[^\"]*\"|AGENT_TOKEN=\"$TOKEN\"|g" "$WRITE_HOOK"

sed -i "s|CONTROLLER_URL=\"[^\"]*\"|CONTROLLER_URL=\"$CONTROLLER_URL\"|g" "$DELETE_HOOK"
sed -i "s|AGENT_TOKEN=\"[^\"]*\"|AGENT_TOKEN=\"$TOKEN\"|g" "$DELETE_HOOK"

# Set permissions for DirectAdmin
echo "Configuring permissions..."
chown diradmin:diradmin "$WRITE_HOOK" "$DELETE_HOOK"
chmod 700 "$WRITE_HOOK" "$DELETE_HOOK"

# Setup 60-second cron job for server heartbeat ping
echo "Setting up 60-second cron heartbeat..."
(crontab -l 2>/dev/null | grep -F -v "dnsadmin/api/v1/agent/heartbeat"; echo "* * * * * curl -s -X POST -H \"X-DNSAdmin-Token: $TOKEN\" $CONTROLLER_URL/api/v1/agent/heartbeat >/dev/null 2>&1") | crontab -

echo "=================================================="
echo " DNSAdmin DirectAdmin integration successfully installed!"
echo " Write hook path: $WRITE_HOOK"
echo " Delete hook path: $DELETE_HOOK"
echo "=================================================="
