#!/bin/bash
# ==============================================================================
# DNSAdmin Plesk Event Handlers Installer
# Target OS: Linux with Plesk
# Usage:
#   curl -sS https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main/install-plesk.sh | bash -s -- --controller-url http://your-controller-ip:5380 --token <your-server-api-key>
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this installation script as root."
  exit 1
fi

show_help() {
  echo "Usage: $0 --controller-url <url> --token <token>"
  echo "Options:"
  echo "  --controller-url   URL of the central DNSAdmin controller"
  echo "  --token            Server API key generated by the controller for this server"
  exit 0
}

# Parse options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --controller-url) CONTROLLER_URL="$2"; shift ;;
    --token) TOKEN="$2"; shift ;;
    -h|--help) show_help ;;
    *) echo "Unknown option: $1"; show_help ;;
  esac
  shift
done

if [ -z "$CONTROLLER_URL" ] || [ -z "$TOKEN" ]; then
  echo "Error: --controller-url and --token are required."
  show_help
fi

# Check if Plesk commands exist
if ! command -v plesk &>/dev/null; then
  echo "Error: Plesk CLI utility ('plesk') not found on this server."
  exit 1
fi

HOOK_DEST="/usr/local/bin/dnsadmin-plesk-hook.sh"
RAW_BASE_URL="https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main"

echo "Downloading Plesk event handler..."
curl -sS -o "$HOOK_DEST" "$RAW_BASE_URL/integrations/plesk-hook.sh?v=$(date +%s)"
curl -sS -o "/usr/local/bin/dnsadmin-plesk-sync-all.sh" "$RAW_BASE_URL/integrations/plesk-sync-all.sh?v=$(date +%s)"

if [ ! -f "$HOOK_DEST" ] || [ ! -s "$HOOK_DEST" ]; then
  echo "Error: Failed to download Plesk hook script."
  exit 1
fi

# Normalize CONTROLLER_URL (strip trailing slash)
CONTROLLER_URL="${CONTROLLER_URL%/}"

# Insert configuration variables
echo "Configuring integration hooks..."
sed -i "s|CONTROLLER_API=\"[^\"]*\"|CONTROLLER_API=\"$CONTROLLER_URL/api/v1/agent\"|g" "$HOOK_DEST"
sed -i "s|AGENT_TOKEN=\"[^\"]*\"|AGENT_TOKEN=\"$TOKEN\"|g" "$HOOK_DEST"

chmod +x "$HOOK_DEST" "/usr/local/bin/dnsadmin-plesk-sync-all.sh"

# Unregister existing event handlers if present to prevent duplication
echo "Cleaning existing Plesk handlers..."
plesk bin event_handler --list | grep "dnsadmin" | awk '{print $1}' | while read -r handler_id; do
  plesk bin event_handler --delete -id "$handler_id" &>/dev/null
done

# Register Event Handlers in Plesk Event Manager
echo "Registering event handlers in Plesk Event Manager..."

# 1. Domain DNS Zone Updated Event
plesk bin event_handler --create -event "Domain DNS zone updated" -priority 50 -user root -command "$HOOK_DEST"
# 2. Subdomain DNS Zone Updated Event
plesk bin event_handler --create -event "DNS zone of a subdomain updated" -priority 50 -user root -command "$HOOK_DEST"
# 3. Domain Alias DNS Zone Updated Event
plesk bin event_handler --create -event "DNS zone of a domain alias updated" -priority 50 -user root -command "$HOOK_DEST"

# 4. Setup 60-second cron job for server heartbeat ping
echo "Setting up 60-second cron heartbeat..."
(crontab -l 2>/dev/null | grep -F -v "dnsadmin/api/v1/agent/heartbeat"; echo "* * * * * curl -s -X POST -H \"X-DNSAdmin-Token: $TOKEN\" $CONTROLLER_URL/api/v1/agent/heartbeat >/dev/null 2>&1") | crontab -

# 5. Create 10-second DNSAdmin Zone Watcher Service
echo "Configuring 10-second DNSAdmin Zone Watcher Daemon..."
WATCHER_SCRIPT="/usr/local/bin/dnsadmin-watcher.sh"
cat << 'EOF' > "$WATCHER_SCRIPT"
#!/bin/bash
HOOK_SCRIPT="/usr/local/bin/dnsadmin-plesk-hook.sh"
CACHE_DIR="/dev/shm/dnsadmin-cache"
mkdir -p "$CACHE_DIR"

log() {
  echo "[DNSAdmin Watcher] $1" >&2
}

scan_and_sync() {
  for dir in "/var/named/run-root/var" "/var/named/run-root/var/named" "/var/named/chroot/var" "/var/named/chroot/var/named" "/var/named"; do
    [ -d "$dir" ] || continue
    find "$dir" -maxdepth 1 -type f ! -name "named.*" ! -name "*.conf" ! -name "*.key" ! -name "*.ca" ! -name "bind.*" ! -name "*.nzf" 2>/dev/null | while read -r filepath; do
      filename=$(basename "$filepath")
      domain="${filename%.db}"
      if [[ "$domain" != *.* ]]; then
        continue
      fi
      current_md5=$(md5sum "$filepath" | awk '{print $1}')
      cache_file="$CACHE_DIR/${domain}.md5"
      if [ -f "$cache_file" ]; then
        old_md5=$(cat "$cache_file")
      else
        old_md5=""
      fi
      if [ "$current_md5" != "$old_md5" ]; then
        log "Detected changes in $domain. Triggering sync..."
        "$HOOK_SCRIPT" "$domain" >/dev/null 2>&1 &
        echo "$current_md5" > "$cache_file"
      fi
    done
  done
}

log "Starting DNSAdmin Zone Watcher Daemon..."
while true; do
  scan_and_sync
  sleep 10
done
EOF

chmod +x "$WATCHER_SCRIPT"

# Install Systemd Service
cat << 'EOF' > /etc/systemd/system/dnsadmin-watcher.service
[Unit]
Description=DNSAdmin Zone Watcher Daemon
After=network.target named.service plesk-bind.service

[Service]
Type=simple
ExecStart=/usr/local/bin/dnsadmin-watcher.sh
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable dnsadmin-watcher &>/dev/null
systemctl restart dnsadmin-watcher &>/dev/null



echo "=================================================="
echo " DNSAdmin Plesk integration successfully installed!"
echo " Handler path: $HOOK_DEST"
echo " Active Plesk Handlers:"
plesk bin event_handler --list | grep "dnsadmin"
echo "=================================================="
