#!/bin/bash
# ==============================================================================
# DNSAdmin Plesk Event Handlers Installer
# Target OS: Linux with Plesk
# Usage:
#   curl -sS https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main/install-plesk.sh | bash -s -- --controller-url http://your-controller-ip:5380 --token <your-server-api-key>
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this installation script as root."
  exit 1
fi

show_help() {
  echo "Usage: $0 --controller-url <url> --token <token>"
  echo "Options:"
  echo "  --controller-url   URL of the central DNSAdmin controller"
  echo "  --token            Server API key generated by the controller for this server"
  exit 0
}

# Parse options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --controller-url) CONTROLLER_URL="$2"; shift ;;
    --token) TOKEN="$2"; shift ;;
    -h|--help) show_help ;;
    *) echo "Unknown option: $1"; show_help ;;
  esac
  shift
done

if [ -z "$CONTROLLER_URL" ] || [ -z "$TOKEN" ]; then
  echo "Error: --controller-url and --token are required."
  show_help
fi

# Check if Plesk commands exist
if ! command -v plesk &>/dev/null; then
  echo "Error: Plesk CLI utility ('plesk') not found on this server."
  exit 1
fi

HOOK_DEST="/usr/local/bin/dnsadmin-plesk-hook.sh"
RAW_BASE_URL="https://raw.githubusercontent.com/bburakguldogan/dnsadmin/main"

echo "Downloading Plesk event handler..."
curl -sS -o "$HOOK_DEST" "$RAW_BASE_URL/integrations/plesk-hook.sh"

if [ ! -f "$HOOK_DEST" ] || [ ! -s "$HOOK_DEST" ]; then
  echo "Error: Failed to download Plesk hook script."
  exit 1
fi

# Insert configuration variables
echo "Configuring integration hooks..."
sed -i "s|CONTROLLER_API=\"[^\"]*\"|CONTROLLER_API=\"$CONTROLLER_URL\"|g" "$HOOK_DEST"
sed -i "s|AGENT_TOKEN=\"[^\"]*\"|AGENT_TOKEN=\"$TOKEN\"|g" "$HOOK_DEST"

chmod +x "$HOOK_DEST"

# Unregister existing event handlers if present to prevent duplication
echo "Cleaning existing Plesk handlers..."
plesk bin event_handler --list | grep "dnsadmin" | awk '{print $1}' | while read -r handler_id; do
  plesk bin event_handler --delete -id "$handler_id" &>/dev/null
done

# Register Event Handlers in Plesk Event Manager
echo "Registering event handlers in Plesk Event Manager..."

# 1. Domain DNS Zone Updated Event
plesk bin event_handler --create -event "Domain DNS zone updated" -priority 50 -user root -command "$HOOK_DEST"
# 2. Subdomain DNS Zone Updated Event
plesk bin event_handler --create -event "DNS zone of a subdomain updated" -priority 50 -user root -command "$HOOK_DEST"
# 3. Domain Alias DNS Zone Updated Event
plesk bin event_handler --create -event "DNS zone of a domain alias updated" -priority 50 -user root -command "$HOOK_DEST"

echo "=================================================="
echo " DNSAdmin Plesk integration successfully installed!"
echo " Handler path: $HOOK_DEST"
echo " Active Plesk Handlers:"
plesk bin event_handler --list | grep "dnsadmin"
echo "=================================================="
