import express from 'express';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';

const app = express();
app.use(express.json({ limit: '10mb' }));

// Configuration from Environment Variables
const PORT = process.env.PORT || 5300;
const TOKEN = process.env.DNSADMIN_TOKEN || 'test-node-token-123';
const CONTROLLER_URL = process.env.DNSADMIN_CONTROLLER_URL || 'http://localhost:5380';
const NODE_NAME = process.env.NODE_NAME || os.hostname();
const ZONES_DIR = path.resolve(process.env.ZONES_DIR || './zones');
const NAMED_CONF_PATH = path.resolve(process.env.NAMED_CONF_PATH || './dnsadmin.zones');
const RELOAD_CMD = process.env.RELOAD_CMD || 'echo "DNS records reloaded successfully"';

// Ensure zones directory exists
if (!fs.existsSync(ZONES_DIR)) {
  fs.mkdirSync(ZONES_DIR, { recursive: true });
}

// Token Verification Middleware
function verifyToken(req, res, next) {
  const token = req.headers['x-dnsadmin-token'];
  if (!token || token !== TOKEN) {
    return res.status(401).json({ error: 'Unauthorized: Invalid token' });
  }
  next();
}

// Main API: Zone Update / Delete
app.post('/api/v1/zone', verifyToken, async (req, res) => {
  const { domain, action, zone_text } = req.body;
  if (!domain || !action) {
    return res.status(400).json({ error: 'domain and action are required' });
  }

  const zoneFilePath = path.join(ZONES_DIR, `${domain}.db`);

  try {
    if (action === 'update') {
      if (!zone_text) {
        return res.status(400).json({ error: 'zone_text is required for update' });
      }
      console.log(`[Agent] Updating zone: ${domain}`);
      fs.writeFileSync(zoneFilePath, zone_text, 'utf8');
    } else if (action === 'delete') {
      console.log(`[Agent] Deleting zone: ${domain}`);
      if (fs.existsSync(zoneFilePath)) {
        fs.unlinkSync(zoneFilePath);
      }
    } else {
      return res.status(400).json({ error: 'Invalid action: must be update or delete' });
    }

    // Rebuild the BIND inclusion config file
    rebuildBindConfig();

    // Trigger BIND reload
    triggerReload((err, output) => {
      if (err) {
        console.error(`[Agent] Reload failed: ${err}`);
        return res.status(500).json({ error: `DNS reload failed: ${err}` });
      }
      console.log(`[Agent] BIND reloaded. Output: ${output.trim()}`);
      res.json({ success: true, message: `Zone ${domain} processed & nameserver reloaded` });
    });

  } catch (err) {
    console.error(`[Agent] Error processing zone ${domain}:`, err);
    res.status(500).json({ error: err.message });
  }
});

// Helper: Rebuild BIND named.conf.local records file
function rebuildBindConfig() {
  const files = fs.readdirSync(ZONES_DIR);
  let configText = '// Generated by DNSAdmin Node Agent. DO NOT EDIT MANUALLY.\n\n';

  for (const file of files) {
    if (file.endsWith('.db')) {
      const domain = file.substring(0, file.length - 3);
      const absoluteDbPath = path.join(ZONES_DIR, file);
      configText += `zone "${domain}" {\n`;
      configText += `    type master;\n`;
      configText += `    file "${absoluteDbPath}";\n`;
      configText += `};\n\n`;
    }
  }

  fs.writeFileSync(NAMED_CONF_PATH, configText, 'utf8');
  console.log(`[Agent] BIND config rebuilt at: ${NAMED_CONF_PATH}`);
}

// Helper: Trigger standard BIND reload command
function triggerReload(callback) {
  exec(RELOAD_CMD, (error, stdout, stderr) => {
    if (error) {
      callback(error.message, null);
    } else {
      callback(null, stdout || stderr || 'Reload successful');
    }
  });
}

// Helper: Calculate CPU usage delta
function getCpuUsage() {
  return new Promise((resolve) => {
    const start = os.cpus();
    setTimeout(() => {
      const end = os.cpus();
      let idleDifference = 0;
      let totalDifference = 0;
      for (let i = 0; i < start.length; i++) {
        const s = start[i];
        const e = end[i];
        const idle = e.times.idle - s.times.idle;
        const total = (e.times.user - s.times.user) +
                      (e.times.nice - s.times.nice) +
                      (e.times.sys - s.times.sys) +
                      (e.times.irq - s.times.irq) +
                      idle;
        idleDifference += idle;
        totalDifference += total;
      }
      const usage = 100 - Math.floor((idleDifference / totalDifference) * 100);
      resolve(isNaN(usage) ? 0 : usage);
    }, 100);
  });
}

// Helper: Calculate RAM usage accurately (especially on Linux /proc/meminfo)
function getRamUsage() {
  try {
    if (process.platform === 'linux' && fs.existsSync('/proc/meminfo')) {
      const meminfo = fs.readFileSync('/proc/meminfo', 'utf8');
      const memTotalMatch = meminfo.match(/^MemTotal:\s+(\d+)\s+kB/m);
      const memAvailableMatch = meminfo.match(/^MemAvailable:\s+(\d+)\s+kB/m);
      if (memTotalMatch && memAvailableMatch) {
        const total = parseInt(memTotalMatch[1], 10);
        const available = parseInt(memAvailableMatch[1], 10);
        const used = total - available;
        const percentage = Math.floor((used / total) * 100);
        return percentage;
      }
    }
  } catch (err) {
    console.warn('[Agent] Error reading /proc/meminfo, falling back to os.freemem():', err.message);
  }
  return Math.floor((1 - os.freemem() / os.totalmem()) * 100);
}

// Send heartbeats to controller every 60 seconds
async function sendHeartbeat() {
  if (!CONTROLLER_URL) return;

  try {
    const cpu = await getCpuUsage();
    const memory = getRamUsage();

    const res = await fetch(`${CONTROLLER_URL}/api/v1/node/heartbeat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-DNSAdmin-Token': TOKEN
      },
      body: JSON.stringify({
        name: NODE_NAME,
        cpu,
        memory
      }),
      signal: AbortSignal.timeout(4000)
    });

    if (!res.ok) {
      console.warn(`[Agent Status] Controller status returned HTTP ${res.status}`);
    }
  } catch (err) {
    console.error(`[Agent Status] Heartbeat failure linking to Controller: ${err.message}`);
  }
}

// Start Server
app.listen(PORT, '0.0.0.0', () => {
  console.log(`DNSAdmin Node Agent running on port ${PORT}`);
  console.log(`Managed BIND Conf: ${NAMED_CONF_PATH}`);
  console.log(`Zones directory: ${ZONES_DIR}`);

  // Rebuild config on boot in case zones were edited/exist
  rebuildBindConfig();

  // Trigger immediate heartbeat and repeat every 60 seconds
  sendHeartbeat();
  setInterval(sendHeartbeat, 60000);
});
